// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:DonVo.FactoryManagement.APIs.Controllers.HRController.UpdateCustomer(System.String,DonVo.FactoryManagement.Models.ViewModels.CustomerView.CustomerVM)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{DonVo.FactoryManagement.Models.ViewModels.CustomerView.WrapperListCustomerVM}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:DonVo.FactoryManagement.APIs.Controllers.HRController.AddCustomer(DonVo.FactoryManagement.Models.ViewModels.CustomerView.CustomerVM)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{DonVo.FactoryManagement.Models.ViewModels.CustomerView.WrapperListCustomerVM}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:DonVo.FactoryManagement.APIs.Controllers.HRController.DeleteCustomer(DonVo.FactoryManagement.Models.ViewModels.CustomerView.CustomerVM)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{DonVo.FactoryManagement.Models.ViewModels.CustomerView.WrapperListCustomerVM}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:DonVo.FactoryManagement.APIs.Controllers.HRController.AddStaff(DonVo.FactoryManagement.Models.ViewModels.Staff.StaffVM)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{DonVo.FactoryManagement.Models.ViewModels.Staff.WrapperStaffListVM}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:DonVo.FactoryManagement.APIs.Controllers.HRController.UpdateSupplier(System.String,DonVo.FactoryManagement.Models.ViewModels.Supplier.SupplierVM)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{DonVo.FactoryManagement.Models.ViewModels.Supplier.WrapperSupplierListVM}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:DonVo.FactoryManagement.APIs.Controllers.MassCrudController.DeleteStock(DonVo.FactoryManagement.Models.ViewModels.Stock.StockVM)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{DonVo.FactoryManagement.Models.ViewModels.Stock.WrapperStockListVM}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:DonVo.FactoryManagement.APIs.Controllers.HRController.DeleteSupplier(DonVo.FactoryManagement.Models.ViewModels.Supplier.SupplierVM)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{DonVo.FactoryManagement.Models.ViewModels.Supplier.WrapperSupplierListVM}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:DonVo.FactoryManagement.APIs.Controllers.HRController.UpdateStaff(System.String,DonVo.FactoryManagement.Models.ViewModels.Staff.StaffVM)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{DonVo.FactoryManagement.Models.ViewModels.Staff.WrapperStaffListVM}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:DonVo.FactoryManagement.APIs.Controllers.HRController.AddToStaff(DonVo.FactoryManagement.Models.ViewModels.Staff.StaffVM)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{DonVo.FactoryManagement.Models.ViewModels.Staff.WrapperStaffListVM}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:DonVo.FactoryManagement.APIs.Controllers.MassCrudController.UpdateStock(System.String,DonVo.FactoryManagement.Models.ViewModels.Stock.StockVM)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{DonVo.FactoryManagement.Models.ViewModels.Stock.WrapperStockListVM}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:DonVo.FactoryManagement.APIs.Controllers.MassCrudController.UpdateCustomer(System.String,DonVo.FactoryManagement.Models.ViewModels.CustomerView.CustomerVM)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{DonVo.FactoryManagement.Models.ViewModels.CustomerView.WrapperListCustomerVM}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:DonVo.FactoryManagement.APIs.Controllers.HRController.AddSupplier(DonVo.FactoryManagement.Models.ViewModels.Supplier.SupplierVM)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{DonVo.FactoryManagement.Models.ViewModels.Supplier.WrapperSupplierListVM}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:DonVo.FactoryManagement.APIs.Controllers.MassCrudController.AddStock(DonVo.FactoryManagement.Models.ViewModels.Stock.StockVM)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{DonVo.FactoryManagement.Models.ViewModels.Stock.WrapperStockListVM}}")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:DonVo.FactoryManagement.APIs.Controllers.MassCrudController.AddCustomer(DonVo.FactoryManagement.Models.ViewModels.CustomerView.CustomerVM)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{DonVo.FactoryManagement.Models.ViewModels.CustomerView.WrapperListCustomerVM}}")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Remove unread private members", Justification = "<Pending>", Scope = "member", Target = "~F:DonVo.FactoryManagement.APIs.Controllers.FactoriesController._context")]
